version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-50-19-221-38.compute-1.amazonaws.com
            database: d7mfo9ibr6rod5
            user: dpngkiobgjvqyo
            password: 9e371f9de87a6945f166c6d9208ed4aa67a7198d299f546b322f3c247a0b0ddf
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true